---
- name: "Install uncomplicated firewall (UFW)"
  apt: pkg={{ item }} state=installed
  with_items:
  - ufw

- name: "Allow SSH"
  ufw:
    rule: allow
    name: "{{ item }}"
  become: true
  with_items:
    - OpenSSH

- name: "More rules"
  ufw:
    rule: allow
    port: "{{ item }}"
  become: true
  with_items:
    - 80
    - 443
    - 5432

- name: "Enable UFW"
  ufw:
    state: enabled
  become: true

- name: Change ssh port
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Port\s"
              line="Port {{ common_ssh_port }}"
              state=present
  notify: 
    - restart ssh

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: PasswordAuthentication no
    state: present
  become: true
  notify: 
    - restart ssh

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: true
  notify: 
    - restart ssh
